### ISSUE TITLE
Installation procedure via PyPI should be removed

### ISSUE THREAD

**Issue by alzaia** [axondeepseg/axondeepseg#109]
I think the AxonDeepSeg installation procedure via PyPI (see http://axondeepseg.readthedocs.io/en/stable/documentation.html#option-1-installing-axondeepseg-in-application-mode-stable-release) should be removed and we should only keep the installation procedure via GitHub (http://axondeepseg.readthedocs.io/en/stable/documentation.html#option-2-installing-axondeepseg-in-development-mode-from-github).

The main reason is because it is harder to maintain, as we need to publish a new wheel on PyPI every time we release a new version of the package. So if the wheel of the last version is not on PyPI, a new user that installs it from PyPI will not have the right version.

**Comment by mathieuboudreau** [comment]
@alzaia do you have any stats of how many/frequently people installed ADS using PyPi vs GitHub to date?

**Comment by alzaia** [comment]
I don't have stats, but I had one user that had bad segmentation results on one of our test samples, and I strongly suspect he installed it from PyPI and had an older version (to be confirmed) .

But thinking more about it, a cloning of the repo would be mandatory to have the notebooks (installation from PyPI does not include the notebooks). And now we are using Jupyter extensively for almost everything on ADS. @perone What do you think about it?

**Comment by perone** [comment]
It's up to you guys, I usually prefer installation through the official PyPI because it's easier, just `pip install axondeepseg`, but if users are familiar with GitHub I don't see any problem. The only problem with recommending GitHub installation is that you can easily lose track of which version they're using because there is no version anymore, just a commit hash that you can use.
I personally use more notebooks just to develop, but then later I usually use command-line tools with arguments or json configurations for running inference, experiments, etc. But that is a matter of personal taste.

**Comment by jcohenadad** [comment]
A workaround wrt. versioning would be to catch the commit hash and include it in some sort of output log file, that users can send us afterwards

**Comment by mathieuboudreau** [comment]
Done
