### ISSUE TITLE
CHANGELOG is not up-to-date

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#126]
We should maintain [CHANGELOG.md](https://github.com/neuropoly/axondeepseg/blob/v1.0/CHANGELOG.md) and redirect to it when creating new releases. For now i suggest we manually add the main changes into the CHANGELOG, and in the future we could use [this function](https://github.com/neuropoly/spinalcordtoolbox/blob/master/install/sct_changelog.py) to generate changelogs automatically, based on PR's labels and milestones (good if we start using them so we could update the changelog retroactively).

**Comment by mathieuboudreau** [comment]
Thanks for pointing this out @jcohenadad, I hadn't really noticed that file I think. Do you want to retroactively add all the previous changes for each [tagged releases](https://github.com/neuropoly/axondeepseg/releases) in it? They are quite sparse in details and in frequency – it could be quite a chore to sort through each commit (since we only recently switched to squash and merges for PRs) to distinguish what was actually done between the tagged versions. Or do you want to start with just adding this last update and move on from there?

**Comment by jcohenadad** [comment]
i would not bother too much and just start with recent updates (e.g. moving the blurb you wrote for 0.6 inside the changelog). thanks!

**Comment by perone** [comment]
PS: remember that we have the Changelog in the documentation now (http://axondeepseg.readthedocs.io/en/stable/documentation.html#changelog)

**Comment by mathieuboudreau** [comment]
@perone thanks for pointing that out – that wasn't indicated as a step in the wiki page on how to create new releases: https://github.com/neuropoly/axondeepseg/wiki/How-to-create-a-new-release

**Comment by mathieuboudreau** [comment]
Closing, we've got it automated for our releases now, and the current version is up-to-date.
