### ISSUE TITLE
Diameter measurements discussion

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#349]
This issue is opened to discuss the different methods used for diameter measurements between ADS and other users protocols.

In ADS, the calculation of the diameter is based on the axon area of the mask. For each axons, the equivalent diameter is computed, which is the diameter of a circle with the same area as the axon. Similarly, ADS calculates the area of each axon+myelin pairs on the mask and its equivalent diameter. The myelin thickness is then calculated from the difference between the axon+myelin equivalent diameter and the axon equivalent diameter.

We recommend to use this method to ensure that a mean diameter is computed that is not bias in any specific direction, and also takes into account that axons do not have a perfectly cylindrical shape.

We received feedback from users with different protocols for manual measurements:
1. Axon and cell diameters are taken from the shortest distance passing through the center of the axon [here](https://github.com/neuropoly/axondeepseg/issues/347#issuecomment-689961633).
2. Another user mentioned by e-mail that they treat the axon as an ellipse and take the minor axis of the ellipse as the axon diameter to account for the sectioning for TEM that is never perfectly orthogonal to the axon resulting in the axons being usually in oblong shapes.

**Comment by mathieuboudreau** [comment]
What is the current consensus on how it's currently (or used to be) done manually in the histology world?

**Comment by Paasu** [comment]
The measurements I performed were done on TEM images of rat optic nerves using ImageJ. The method echoed what the other user tries; measuring the minor axis of the 'ellipse' mainly because it gets the minimum axon/fibre diameters. The minimum axon diameter was used to reduce the skewing of data accounted by the oblong-like shapes of some of the fibres. When it comes to injured nerves however, they tend to produced decompaction within the myelin while regenerating; myelin thickness is very different and g-ratio doesn't always reflect accurately the relationship between axon and myelin. Here are a few studies that used the methodology as described above when looking at rat neurons in TEM:

Payne et al: https://pubmed.ncbi.nlm.nih.gov/21381867/
 - Measured minimum axon and fibre diameter
 - Calculated myelin thickness by subtracting axon diameter from fibre diameter and dividing by 2
 - Minimum was calculated to avoid artificial skewing of data due to axons projecting at an oblique angle
 - Only myelin thickness of normally myelinated axons were calculated to reduce skew in data
 
Payne et al: https://pubmed.ncbi.nlm.nih.gov/22879411/
 - Measured minimum axon diameter
 - Minimum was calculated to avoid artificial skewing of data due to axons projecting at an oblique angle
 - G-ratio measured only only for normally myelinated axons
 
Fehily et al: https://pubmed.ncbi.nlm.nih.gov/30702755/
 - Measured minimum axon, fibre diameter and myelin thickness
 - Minimum was calculated to avoid artificial skewing of data due to axons projecting at an oblique angle
 - Minimum myelin thickness was averaged between 2 measurements taken
 - For decompacted axons, minimum fibre diameter was measured in the same location as the axon diameter including decompaction and myelin sheath

The studies also show a method of discriminating axons with decompacted myelin for analysis.
Myelinated axons
 - 85% of the axon is wrapped by myelin
 - Wrapped by a thick, compact high electron density myelin

Lightly myelinated axons
 - Wrapped by thick, compact, low electron density myelin

Partially decompacted axons
 - Proportion (>35%) of axon wrapped by thick, decompacted, high electron density myelin

Fully decompacted axons
 - Wrapped by thin, multiple layers of low electron density myelin

As for axon diameter, ADS seems to treat it as a circle and derive the diameter based off that which is a good way to remove bias like mentioned in the studies. At the same time however, there would be a difference in axons that are oblong shaped where a larger axon diameter would be produced by ADS and a smaller one produced by taking the minimum diameter of the 'oblong'. Perhaps there is a way to contextualize each sets of diameters to gain a deeper understanding of the difference in results or maybe treating axons as an ellipse might prove better? What do you guys think?

**Comment by jcohenadad** [comment]
thank you for the literature review @Paasu, these are indeed solid arguments for offering the 'min diameter' feature in ADS. That should be fairly easy to implement.

**Comment by mathieuboudreau** [comment]
Done in #363 and #399
