### ISSUE TITLE
Automatize PyPI package creation with github action

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#353]
Automatize pypi package: example here: https://github.com/ivadomed/ivadomed/actions/runs/267724393/workflow

**Comment by mathieuboudreau** [comment]
Just as a heads up for this - we'll have to be extra vigilent about the version numbers we save in pipy if we do this. If someone accidentally slips in a type (e.g. version 33.0 instead of 3.3.0) and it is built and pushed to pipy, there is no way to "roll back" the latest version on pipy - it would then always be version 33.0 when pulled with `pip install axondeepseg` even if we push another version of lets say 3.4.0.

Maybe there's a GitHub action to do this version check and fail the build for this type of mistake?

**Comment by jcohenadad** [comment]
> Maybe there's a GitHub action to do this version check and fail the build for this type of mistake?

good idea. We can probably add a check in [this example github action](https://github.com/neuropoly/gifmaker/actions/runs/238346047/workflow), which is very useful (ie: triggered when creating a release on github).

**Comment by mathieuboudreau** [comment]
Stale - no longer using pipy
