### ISSUE TITLE
Visually Distinguishing Adjacent Myelin Wraps and Ellipse Minor Access in Fsleyes

### ISSUE THREAD

**Issue by n-amb** [axondeepseg/axondeepseg#396]
Hello, 

Within my image set, there are cases of adjacent myelin wraps contacting each other (see screen grab below). The morphometric calculation typically yields reasonable measurements in these cases. However, I think it would be useful to visually confirm that adjacent myelin wraps are in fact distinct within Fsleyes. Perhaps this means being able to select a specific ROI/axon-myelin instance and toggle them off and on, or that the myelin overlay created includes multiple colors that can be used to distinguish discrete myelin wraps. 
<img width="364" alt="Screen Shot 2020-11-15 at 8 49 29 PM" src="https://user-images.githubusercontent.com/71902782/99214046-1071ec80-2784-11eb-90f8-4d309b95bd96.png">

In addition, a previous post alluded to the implementation of the ellipse minor axis morphometric measurement to the Fsleyes plugin. Is this option available with the current version? 

Thanks for considering these feature requests!

**Comment by Stoyan-I-A** [comment]
Coincidentally, the team discussed about these topics today.

For the visual distinction between two axon-myelin objects, we used to have a feature that did something like that a while ago. We removed it because its purpose wasn't clear at the time but now we would like to explore the possibility of adding such this feature to a new interactive user interface similar to this one: https://dash-gallery.plotly.host/dash-label-properties/ .
That being said, this won't be done on the short term.

As for the ellipse minor axis, we are working on it. You can follow the progress in #381 .

**Comment by mathieuboudreau** [comment]
Stale
