### ISSUE TITLE
Test other software package offering "easy label" and segmentation of images

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#404]
### Context

A couple of recent publications and software packages offer the possibility to upload an image in a GUI (e.g. ImageJ, FIJI, etc.), perform an easy labeling, train a model on-the-fly and apply to the rest of the image (or other images).

Examples of articles include:
- [falk2018.pdf](https://github.com/neuropoly/axondeepseg/files/5604871/falk2018.pdf)
- [haberl2018.pdf](https://github.com/neuropoly/axondeepseg/files/5604873/haberl2018.pdf)
- [s41592-019-0582-9.pdf](https://github.com/neuropoly/axondeepseg/files/5604880/s41592-019-0582-9.pdf)

And software:
- https://github.com/qupath/qupath/wiki
- https://imagej.nih.gov/ij/
- https://fiji.sc/
- https://microdraw.pasteur.fr/
- https://opensource.google/projects/neuroglancer

### Proposal

It would be nice to assess the effectiveness of these packages wrt. what ADS can offer in terms of:
- user friendliness
- performance (Dice score)
- time spent for training/prediction
- outputs (morphometric calculations, etc.)

### Dataset

To do this comparison, we propose to use the following dataset, which includes an image and its ground truth (for training), and another image without ground truth (for testing): [data_train-test.zip](https://github.com/neuropoly/axondeepseg/files/5604892/data_train-test.zip)

Other possible datasets:
- nerve seg (email 2020-12-03)

**Comment by hermancollin** [comment]
We just found out about the [empanada](https://github.com/volume-em/empanada) which leverages `napari` for their GUI: https://github.com/napari/napari 
As discussed in #544, maybe this would be a good target to migrate the FSLeyes plugin. 

`napari` is built on top of Qt whereas `fsleyes` uses wxPython. Comparing these 2 frameworks, it seems like Qt is much more cross-platform-friendly, as it uses approximations instead of native widgets, which is what wxPython leverages. The disadvantage is that, while being theoretically more "accurate", native widgets require platform-specific changes in the GUI code. However, Qt acts as a much better abstraction layer over the OS.

Also tagging @Stoyan-I-A who might have some thoughts about this.

**Comment by Stoyan-I-A** [comment]
I have heard of `napari` in the past but never tested it. It could be a nice GUI option to explore. The fact that almost all of its source code is in Python means that the learning curve for developing a plugin for it should be less steep.
