### ISSUE TITLE
Terminal issues with fsleyes 

### ISSUE THREAD

**Issue by AlmudenaRobledo** [axondeepseg/axondeepseg#416]
Hello, 
I updated my Mac software to IOS Catalina and this changed my terminal to zsh and my commands don't work anymore. At first it gave me a command not found error and  I managed to add conda to the path and got conda to work but I can no longer open fsleyes. I tried reinstalling and updating but nothing. The error it gives me is this: 
Last login: Tue Dec  8 12:46:46 on ttys000
(base) Almudena@Almudenas-MacBook-Air ~ % conda activate ads_venv
(ads_venv) Almudena@Almudenas-MacBook-Air ~ % fsleyes
Using TensorFlow backend.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
  np_resource = np.dtype([("resource", np.ubyte, 1)])
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
(ads_venv) Almudena@Almudenas-MacBook-Air ~ %

**Comment by mathieuboudreau** [comment]
Hi @AlmudenaRobledo,

The problem(s) you're experiencing don't appear to be related to the AxonDeepSeg software directly, but to some of the dependencies. I'll do my best to guide you in the right direction, but you may need to reach out for help directly to these dependencies if we can't resolve it here.

The main error that you're experiencing seems to be related to wxPython, which is needed so that graphical user interfaces can work when inside a virtual environment. See here: https://stackoverflow.com/questions/48531006/wxpython-this-program-needs-access-to-the-screen

I'm not sure why this would only have started happening to you after your MacOS upgrade though; it's possible you have a second problem where your old bash_profile hasn't been moved to your ZSH profile properly.

To start off, I'd recommend you try installing wXPython inside your venv: `conda install wxPython`.
