### ISSUE TITLE
How to use my trained model to segment data

### ISSUE THREAD

**Issue by Paasu** [axondeepseg/axondeepseg#425]
I would like to know how to use my trained model to segment data. I have trained ADS to my liking and I want to know how to use that to segment the batch of images I have. Does it do it automatically or do I have to do something?

**Comment by mathieuboudreau** [comment]
Thanks Paasu!

@mariehbourget @vs74 the issue here is the need to have functionality to easily add their trained model so that it's accessible by other APIs. RIght now, I think it's not centralized, ideally we'd need to only add the model to a folder and then add that model in one place in the code (or in a file that lists all the model) + some of the features (e.g. default pizel size).

**Comment by jcohenadad** [comment]
@Paasu thank you for reaching out. If you have a question in the future, could you please post there:
https://github.com/neuropoly/axondeepseg/discussions?discussions_q=category%3A%22Questions+about+using+ADS%22

thank you 😊

**Comment by mariehbourget** [comment]
Hi @Paasu!

At the moment, the best way to segment multiple images with a new trained model is to use the `notebook 00-getting_started.ipynb`
In section 2.2 “Launch the segmentation of the image.”, you can use the `axon_segmentation` function.

For example: `prediction = axon_segmentation([path_testing], [filename_in], path_model, config_network, segmentations_filenames = [filename_out], acquired_resolution=0.1, resampled_resolutions=0.1, verbosity_level=3)`

- `[path_testing]` is a folder containing all the images to segment
- `[filename_in]` is a list of the image filenames.
- `segmentations_filenames = [filename_out]` is a list of the segmentation filenames outputed by the function.
- `acquired_resolution` should correspond to the pixel size in micrometer of your images. This argument is not required if you have the pixel_size_in_micrometer.txt in the same folder as your testing image.
- `resampled_resolutions` should be the same as the `general_pixel_size` you used when creating the patches for your training

Let us know if you have any questions.

**Comment by mariehbourget** [comment]
> the issue here is the need to have functionality to easily add their trained model so that it's accessible by other APIs. RIght now, I think it's not centralized, ideally we'd need to only add the model to a folder and then add that model in one place in the code (or in a file that lists all the model) + some of the features (e.g. default pizel size).

@mathieuboudreau, currently we cannot segment with a new trained model with the CLI because of the resampling resolution (hard-coded to the default models value). I opened a new issue regarding this #428. There was already a similar issue for this with fsleyes here #334.

**Comment by mathieuboudreau** [comment]
yup I know. How difficult do you think it would be to do it as a quickly for @Paasu , or to give him instructions on how to do it? I don't think it's worth our time to refactor the code now to resolve that issue since I'm assuming it will be fixed by the IVADOMED integration in the coming months.

**Comment by mathieuboudreau** [comment]
Or I guess, the only real functionality that @Paasu needs/wants is a way to segment folders with his custom model; the training notebook we provide only has instructions for doing a single image. Would it be easy for Paasu to use the segment_folders function from inside a notebook instead of the CLI like he's asking for?

**Comment by vs74** [comment]
> Or I guess, the only real functionality that @Paasu needs/wants is a way to segment folders with his custom model; the training notebook we provide only has instructions for doing a single image. Would it be easy for Paasu to use the segment_folders function from inside a notebook instead of the CLI like he's asking for?

I tried testing the 2nd argument (filename_in) of [axon_segmentation](https://github.com/neuropoly/axondeepseg/blob/3862aa223bfe1710ba4dd68965df8b131c503755/AxonDeepSeg/apply_model.py#L186) function that would enable to segment all the images in a given folder. 

For instance, all the images I needed to segment are present under `images_to_segment` directory. The images which were present were:

`1.png`
`2.png`
`3.png`
.......
`10.png`

For this, I  set the second argument as [`1.png`, `2.png`, `3.png`, ..., `10.png`].I tried to segment all the images, but unfortunately this function throws out an error. 

@mariehbourget have you tried segmenting all the images in a given folder automatically using this functionality?

**Comment by vs74** [comment]
> yup I know. How difficult do you think it would be to do it as a quickly for @Paasu , or to give him instructions on how to do it? I don't think it's worth our time to refactor the code now to resolve that issue since I'm assuming it will be fixed by the IVADOMED integration in the coming months.

It won't be that time consuming or difficult in my opinion ( 1-2 days max in my opinion), but I agree with you that since we would be moving towards ivadomed integration, we shouldn't spend time or effort (implementing, testing and documenting it ).

**Comment by mariehbourget** [comment]
> @mariehbourget have you tried segmenting all the images in a given folder automatically using this functionality?

@vs74,  You are right, I have the same error. Sorry, I forgot some details yesterday. To make it work, I create a list of filenames, and then use it in a loop to read each filename_in individually and assign a filename_out. As I mentioned, all the images to segment must be in the same folder.

1. First, I create a list with all the files in the folder: 
```
img_files = [file for file in path_testing.iterdir() if (file.suffix.lower() in ('.png'))]
filenames_in = [str(file.name) for file in img_files]
```
2. Then I use a loop to run the function on a single image and assign a `filename_out` (I add `_ADS` at the end) like this:
```
for filename_in in filenames_in:
    filename_out = filename_in.replace(".png", "_ADS.png")
    prediction = axon_segmentation([path_testing], [filename_in], path_model, config_network, segmentations_filenames = [filename_out], acquired_resolution=0.1, resampled_resolutions=0.1, verbosity_level=3)
```


> Would it be easy for Paasu to use the segment_folders function from inside a notebook instead of the CLI like he's asking for?

@mathieuboudreau, It would be possible but requires more changes to the notebook because the `segment_folders` function segments only 1 folder and is used in a loop from the CLI main. So short answer, it is easier with the `axon_segmentation` method but requires all images to be in the same folder.

I mentioned the CLI yesterday because in my opinion, apart from the `axon_segmentation` method I suggested, it would be the easiest/fastest way to fix the issue.

**Comment by mariehbourget** [comment]
Closing this issue.
With the ivadomed implementation, custom trained models can now be use to segment images via the CLI with the `-m` argument as documented here: https://axondeepseg.readthedocs.io/en/latest/documentation.html#segmentation
