### ISSUE TITLE
What should the default axon shape be: circle or ellipse(morphometrics) ?

### ISSUE THREAD

**Issue by vasudev-sharma** [axondeepseg/axondeepseg#436]
As discussed in our previous meeting, we need to have consensus what the default axon shape should be for morphometrics computation . In order to determine that, I have tested the feature (#399) on the example test data as mentioned in RTD (see [here](https://axondeepseg.readthedocs.io/en/latest/documentation.html#example-dataset)). 

The dataset consists of 
- 1st SEM test image
     - image1_SEM
     - image2_SEM
- 2nd SEM test image
    - image1_SEM 
- 1st TEM test image
    - image1_TEM

**Morphometrics Analysis on these images**

- 1st SEM test image (**image1_SEM**)

![image](https://user-images.githubusercontent.com/31419210/104012160-5a4fdf80-51d5-11eb-9394-6770808d43ae.png)

      - When axon shape is set as circle.
      

  | gratio | axon_area | myelin_area |  ![axon_diam](https://via.placeholder.com/15/f03c15/000000?text=+) `axon_diam` |  ![myelin_thickness](https://via.placeholder.com/15/f03c15/000000?text=+) `myelin_thickness` | axonmyelin_area
-- | -- | -- | -- | -- | -- | --
23 | 0.76019 | 38.318 | 27.9888 | 6.98484 | 1.101719 | 66.3068
41 | 0.50516 | 2.4108 | 7.0364 | 1.752006 | 0.858107 | 9.4472
44 | 0.694327 | 30.0713 | 32.3057 | 6.187727 | 1.362056 | 62.377
51 | 0.683596 | 14.1463 | 16.1259 | 4.244011 | 0.982176 | 30.2722
72 | 0.669229 | 4.6305 | 5.7085 | 2.428114 | 0.600056 | 10.339

[image1_SEM_morphometrics_circle.xlsx](https://github.com/neuropoly/axondeepseg/files/5777130/image1_SEM_morphometrics_circle.xlsx)

     - When axon shape is set as an ellipse
    

  | gratio | axon_area | myelin_area |  ![axon_diam](https://via.placeholder.com/15/f03c15/000000?text=+) `axon_diam` |  ![myelin_thickness](https://via.placeholder.com/15/f03c15/000000?text=+) `myelin_thickness`  | axonmyelin_area
-- | -- | -- | -- | -- | -- | --
23 | 0.76019 | 38.318 | 27.9888 | 4.617765 | 0.971211 | 66.3068
41 | 0.50516 | 2.4108 | 7.0364 | 1.584517 | 0.842758 | 9.4472
44 | 0.694327 | 30.0713 | 32.3057 | 5.240084 | 1.384566 | 62.377
51 | 0.683596 | 14.1463 | 16.1259 | 3.620902 | 0.881783 | 30.2722
72 | 0.669229 | 4.6305 | 5.7085 | 1.542883 | 0.555395 | 10.339

[image1_SEM_morphometrics_ellipse.xlsx](https://github.com/neuropoly/axondeepseg/files/5777126/image1_SEM_morphometrics_ellipse.xlsx)

<hr>

- 1st SEM test image (**image2_SEM**)

![image](https://user-images.githubusercontent.com/31419210/104014381-ed3e4900-51d8-11eb-8106-936311559a18.png)

      - When axon shape is set as circle.
      

  | gratio | axon_area | myelin_area | ![axon_diam](https://via.placeholder.com/15/f03c15/000000?text=+) `axon_diam` |  ![myelin_thickness](https://via.placeholder.com/15/f03c15/000000?text=+) `myelin_thickness`  | axonmyelin_area
-- | -- | -- | -- | -- | -- | --
95 | 0.631449 | 21.1926 | 31.9579 | 5.194541 | 1.515919 | 53.1505
105 | 0.67661 | 3.0251 | 3.5828 | 1.962569 | 0.469012 | 6.6079
108 | 0.691071 | 44.8188 | 49.0269 | 7.554142 | 1.688458 | 93.8457
123 | 0.598044 | 10.9343 | 19.6378 | 3.731217 | 1.253911 | 30.5721
131 | 0.676415 | 39.2418 | 46.5257 | 7.068537 | 1.690733 | 85.7675

[image2_SEM_morphometrics_circle.xlsx](https://github.com/neuropoly/axondeepseg/files/5777141/image2_SEM_morphometrics_circle.xlsx)

      - When axon shape is set as an ellipse
      

  | gratio | axon_area | myelin_area |  ![axon_diam](https://via.placeholder.com/15/f03c15/000000?text=+) `axon_diam` |  ![myelin_thickness](https://via.placeholder.com/15/f03c15/000000?text=+) `myelin_thickness` | axonmyelin_area
-- | -- | -- | -- | -- | -- | --
95 | 0.631449 | 21.1926 | 31.9579 | 4.679203 | 1.456329 | 53.1505
105 | 0.67661 | 3.0251 | 3.5828 | 1.567248 | 0.469609 | 6.6079
108 | 0.691071 | 44.8188 | 49.0269 | 5.891441 | 1.549287 | 93.8457
123 | 0.598044 | 10.9343 | 19.6378 | 2.244691 | 1.245489 | 30.5721
131 | 0.676415 | 39.2418 | 46.5257 | 5.924539 | 1.623364 | 85.7675

[image2_SEM_morphometrics_ellipse.xlsx](https://github.com/neuropoly/axondeepseg/files/5777145/image2_SEM_morphometrics_ellipse.xlsx)

<hr>

- 1st TEM test image (**image1_TEM**)

![image](https://user-images.githubusercontent.com/31419210/104010774-0fcd6380-51d3-11eb-8de2-b84d069406fe.png)

      - When axon shape is set as circle.

  | gratio | axon_area | myelin_area |  ![axon_diam](https://via.placeholder.com/15/f03c15/000000?text=+) `axon_diam` |  ![myelin_thickness](https://via.placeholder.com/15/f03c15/000000?text=+) `myelin_thickness` | axonmyelin_area
-- | -- | -- | -- | -- | -- | --
14 | 0.730813 | 0.286975 | 0.250344 | 0.604473 | 0.111326 | 0.537319
16 | 0.718671 | 0.2737 | 0.256225 | 0.590327 | 0.115544 | 0.529925
22 | 0.844741 | 1.3593 | 0.545581 | 1.315566 | 0.120897 | 1.904881
35 | 0.761378 | 0.1833 | 0.1329 | 0.483099 | 0.075704 | 0.3162
39 | 0.640557 | 0.1667 | 0.239575 | 0.460705 | 0.12926 | 0.406275

[image1_TEM_morphometrics_circle.xlsx](https://github.com/neuropoly/axondeepseg/files/5777151/image1_TEM_morphometrics_circle.xlsx)

         - When axon shape is set as an ellipse
  
  | gratio | axon_area | myelin_area |  ![axon_diam](https://via.placeholder.com/15/f03c15/000000?text=+) `axon_diam` |  ![myelin_thickness](https://via.placeholder.com/15/f03c15/000000?text=+) `myelin_thickness`  | axonmyelin_area
-- | -- | -- | -- | -- | -- | --
14 | 0.730813 | 0.286975 | 0.250344 | 0.539991 | 0.106854 | 0.537319
16 | 0.718671 | 0.2737 | 0.256225 | 0.458162 | 0.107747 | 0.529925
22 | 0.844741 | 1.3593 | 0.545581 | 1.19527 | 0.119756 | 1.904881
35 | 0.761378 | 0.1833 | 0.1329 | 0.458095 | 0.083194 | 0.3162
39 | 0.640557 | 0.1667 | 0.239575 | 0.403173 | 0.098707 | 0.406275

[image1_TEM_morphometrics_ellipse.xlsx](https://github.com/neuropoly/axondeepseg/files/5777150/image1_TEM_morphometrics_ellipse.xlsx)

<hr>

      
As you can clearly see that for the columns( **`axon_diam`** and **`myelin thickness`**), there is indeed a difference in the values when we select axon shape as `circle` or `ellipse`. But looking at these values, I am not sure how significant these differences are. So, I need @mathieuboudreau  or @jcohenadad your insights on this.

**Comment by jcohenadad** [comment]
wow, the difference is quite dramatic. Could you please post the image showing the axons "0" (big change) and "4" (small change) for image1_SEM? I'd like to get a sense of the numbers by comparing with the images.

Also, could you show us the segmented image (with axon numbers) for image1_TEM? there are some diameters that are suspiciously small (0.01µm)

**Comment by vs74** [comment]
> wow, the difference is quite dramatic. Could you please post the image showing the axons "0" (big change) and "4" (small change) for image1_SEM? I'd like to get a sense of the numbers by comparing with the images.
> 
> Also, could you show us the segmented image (with axon numbers) for image1_TEM? there are some diameters that are suspiciously small (0.01µm)

When I looked at the images of the previous first 5 axon/myelin instances ["0", "1", "2", "3" "4] , I decided to remove them in the embedded table of my previous comment because these instances were mostly present at the top border of the image, which were either very small to look at or were either sliced, and I think this won't be an accurate representation of the morphometrics.


Instead of that, I manually chose 5 instances present mostly in the middle of the images and updated it in the embedded tables of my comment, so that we can look at these instances clearly and decide what's the best choice. ( If you wish to look at the morphometrics of earlier instances ["0", "1", "2", "3" "4], you can refer the excel files. )

 I've uploaded the images in my previous commment. The images: `image1_SEM` and `image2_SEM` are zoomed segmented images since when I tried to upload the entire image the numbering on individual instances becomes blurry. 

Also, in order to understand the complete picture and make a decision regarding the axon shape, I recommend to look at the morphometrics excel sheets as well.

**Comment by jcohenadad** [comment]
thank you @vs74 , these number look more reasonable now. I think I would change the default for the "ellipse" based approach, given that it seems this is what most ppl are using. What do you think @mathieuboudreau @mariehbourget ?

**Comment by mathieuboudreau** [comment]
> thank you @vs74 , these number look more reasonable now. I think I would change the default for the "ellipse" based approach, given that it seems this is what most ppl are using. What do you think @mathieuboudreau @mariehbourget ?

Yup, I agree with this. I'd like it if we could also add this information in some key locations throughout the project (e.g. README, RTD, Notebooks, and maybe even in some comments in the code) too so that people don't report the wrong information in their publications after using the software.

**Comment by mariehbourget** [comment]
I disagree with the default being changed to ellipse. Now, people are using morphometrics with “circle” as the default. From a user point of view, it seems dangerous to suddenly change the default behavior, it could very easily lead to error while reporting results. In my opinion, documentation or warning can’t fully prevent those errors.

For example, if we go with “ellipse” as the default. Someone using the current notebook would have to change the call to “get_axon_morphometrics” to add the axon_shape=”circle”, otherwise, their results will change from previous computation.

What I would suggest is to keep the default as “circle”, which seems to be less used by our current users, but is still a valid approach as suggested by our litterature review on the topic.

I think it would also be essential to add information in the notebook and the code regarding the meaning of the shape for computation i.e. circle=equivalent diameter and ellipse=minor axis.
Later, this information should also be included in RTD when morphometrics are added to CLI in #434.

**Comment by mathieuboudreau** [comment]
Closing, we kept the default shape circle.
