### ISSUE TITLE
Testing: AxonDeepSeg CLI doesn't test `default_TEM` model.

### ISSUE THREAD

**Issue by vasudev-sharma** [axondeepseg/axondeepseg#459]
The CLI tests for our `default_SEM` are covered by AxonDeepSeg. However, our `default_TEM model` is not tested by the CLI see [here](https://github.com/neuropoly/axondeepseg/blob/3bcc87d29816d881dcc4b0eda5f075cdcb564544/test/test_segment.py#L183-L264).  

Is there a particular reason we are not testing our **TEM model** or is it just that these tests are skipped?

**Comment by mathieuboudreau** [comment]
I believe it's because I didn't feel it was the role of any tests to evaluate the models themselves. I used default_SEM to quickly test some of the code that uses it, but it actually doesn't check that the model itself is good, so I saw not use to do the same for the TEM.

I can maybe be convinced otherwise though, if there is overwhelming support for testing the models in tests (but that might slow the unit/integration/functional tests on Travis).

**Comment by vs74** [comment]
It is true that we cannot test the models (how well they perform on the segmentations); the tests for the CLI only serve to check whether the model breaks the functionality.

Also, I concur with you that including tests adds additional overhead, which might slow up testing on Travis. So, for now, we might not need additional tests for the specific models.

I brought up this issue because I was thinking add tests for the peripheral nerves segmentation model (PR #457), specifically for the CLI. But considering the additional overhead for Travis and how long we might keep Simeon's model as part of our default models, I might not add tests in my PR.

**Comment by jcohenadad** [comment]
we could have more extensive tests, ran e.g. once a day nightly, that would include those functional tests. i think it is important to test all models-- what if, e.g., the model changes one day? or if one library screws the prediction of one particular model? we want to catch that.

some useful reference of nightly cron job for SCT:
- https://github.com/neuropoly/spinalcordtoolbox/issues/2923
- https://github.com/neuropoly/spinalcordtoolbox/issues/2674

tagging @joshuacwnewton so he is aware of this discussion

**Comment by mathieuboudreau** [comment]
Good point! Maybe we should evaluate the dice coefficient against the test datasets as an assertion for each model? It will fail whenever we update models, but at least we'll be aware ASAP otherwise.

**Comment by vs74** [comment]
I agree that we should add tests to evaluate the model's performance and see if they are breaking or not. In my opinion, tests should be added once the models have been integrated with IVADOMED to avoid redoing the same work. But I am not sure to which side ADS or IVADOMED tests would be added.

**Comment by jcohenadad** [comment]
> But I am not sure to which side ADS or IVADOMED tests would be added.

definitely on the ADS side (ie: end-user)

**Comment by mathieuboudreau** [comment]
Closing, stale and not going to be implemented.
