### ISSUE TITLE
Create and share Linux images with ADS pre-installed for releases?

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#496]
Following up on @Stoyan-I-A 's instructions for running ADS with FSLeyes on a Windows computer ([see here](https://github.com/neuropoly/axondeepseg/discussions/495#discussioncomment-550544)), I'm wondering if it may be worth it to create and share a Linux OS image with ADS & FSLeyes already installed. This could lower the hurdle for users to install this (they would more or less simply need to download VirtualBox, download our image, and run it), as one user already hinted that it sounds a bit complicated to do from scratch [here](https://github.com/neuropoly/axondeepseg/discussions/495#discussioncomment-551677).

Thoughts?

**Comment by jcohenadad** [comment]
I like the idea. This is what we did for SCT in the past. Problem arose when the VM was no more updated, users were complaining, blablabla.

so if we go that route, we need to automatize the update of the VM across stable releases. @dyt811 @joshuacwnewton @kousu @Ainsleigh ideas? thoughts?

**Comment by vs74** [comment]
> Following up on @Stoyan-I-A 's instructions for running ADS with FSLeyes on a Windows computer (see here), I'm wondering if it may be worth it to create and share a Linux OS image with ADS & FSLeyes already installed. This could lower the hurdle for users to install this (they would more or less simply need to download VirtualBox, download our image, and run it), as one user already hinted that it sounds a bit complicated to do from scratch here.

> Thoughts?

I too am in the favour of the idea, but what about Docker images instead of VM's?

**Comment by dyt811** [comment]
From what I understood, VM approach is being prioritized over Docker because of Docker FSLEye setup has issue with connect/setting up external display on especially Windows. There are open source tools like https://www.packer.io/ that can potentially easily allow build into both Docker images and VMs. Since these are infrastructure as code approaches, I think they should be quite robust in terms of automation and maintanability over time

We probably should build some small proof of concept of VM build process with various tools such as Packer. Here is a good list of potential candidates we can toy around with. https://docs.openstack.org/image-guide/create-images-automatically.html

**Comment by mathieuboudreau** [comment]
Stale, closing
