### ISSUE TITLE
Is axondeepseg compatible with anisotropic pixel sizes, and if not how to we do so?

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#515]
e.g.
* Patching/training?
* segmentation
* calculating morphometrics

**Comment by mariehbourget** [comment]
Currently in ADS, there is only one isotropic pixel size value.
In ivadomed for patching, training and segmentation, the code will be compatible with anisotropic 2D or 3D values, provided as a 2 or 3-numbers array.
With the upcoming integration of ADS/ivadomed, we should concentrate our efforts on how to deal with anisotropic pixels sizes for calculating morphometrics.

**Comment by mathieuboudreau** [comment]
Unless `skimage` (the package we use to calculate things like area and perimeter) has an option for anisotropic pixels (I googled and couldn't find anything), then I think what we'd need to do is resample the images (internally, temporary files or data structure) so that they have anisotropic pixel sizes prior to calculating the morphometrics.

**Comment by hermancollin** [comment]
Now that the ivadomed integration is done, models can now be trained using anisotropic pixel sizes (resolution/patch size).

However, in #620, this discussion was raised again because anisotropic pixel sizes in the model config make it harder for us to pre-compute the resampled image size before applying the model (i.e. to verify if the resampled image fits in the model patch). It was decided that, for now, anisotropic pixel sizes will not be supported (error is thrown before segmentation).

This should not have an impact on any current use case, because there was already no support for anisotropic resolution during morphometrics. If users really want to segment with such models, they can always use the ivadomed `--segment` command (for now).

**Comment by mariehbourget** [comment]
> This should not have an impact on any current use case, because there was already no support for anisotropic resolution during morphometrics. If users really want to segment with such models, they can always use the ivadomed `--segment` command (for now).

Thanks @hermancollin for the update.

Regarding the `--segment` command, it is somewhat not easy to use outside of ivadomed because it needs a BIDS structure.

For future reference, I'm going to link an ivadomed issue here regarding the difference between the command `--segment` and the `segment_volume` API: https://github.com/ivadomed/ivadomed/issues/1002

**Comment by mathieuboudreau** [comment]
Stale
