### ISSUE TITLE
Resolve RTD warnings and set "fail on warnings" to true

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#579]
See this discussion: https://github.com/neuropoly/axondeepseg/pull/578#discussion_r741538912

View warnings in the last step here: https://readthedocs.org/projects/axondeepseg/builds/15166200/

**Comment by joshuacwnewton** [comment]
Thankfully these look super quick to fix. Of the 6 warnings:

* 2 involve header underline length (2s fix!)
* 4 involve instances of `:scale: 35%` --> I think you could replace this with [`:figwidth:`](https://docutils.sourceforge.io/docs/ref/rst/directives.html#figure) easily enough, which will scale with the size of the page. Or you could just remove this setting entirely, since it's already being ignored. :sweat_smile:

**Comment by mathieuboudreau** [comment]
Stale

**Comment by joshuacwnewton** [comment]
Even though this is stale, I am happy to self-assign this and take care of the RTD warnings, assuming they are as easy as I described them to be in 2021. :stuck_out_tongue_closed_eyes:
