### ISSUE TITLE
[Morphometrics] When a zero division error occurs, set a flag value in the table to warn the user

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#596]
As discussed internally, we need improvements on the morphometric values table to warn the user when there is some unphysical behaviour. This should include a flag value in the table to warn the user, but could also mean setting other values to 0 or NaN.

**Comment by Stoyan-I-A** [comment]
Just adding a comment here as a reminder that if we decide to add NaNs to the axon diameter, we will need to modify the calls to the function used to generate the image with the axon numbers because the mean diameter is a parameter used to determine the font size of the numbers. We'll just need to make sure to ignore NaNs when computing the mean diameter in places like [this](https://github.com/neuropoly/axondeepseg/blob/805868e39eddf620c9f3d60d313cadffb1121bfb/AxonDeepSeg/morphometrics/compute_morphometrics.py#L198).

**Comment by mathieuboudreau** [comment]
Stale
