### ISSUE TITLE
RuntimeError: "length_2D" must be smaller or equal to image dimensions after resampling.

### ISSUE THREAD

**Issue by GrimmSnark** [axondeepseg/axondeepseg#604]
Hello,

So I get the following error when I am trying to process an image with version 4.0 of the code. This only occurs with the BF and SEM models. 

`File "/home/msavage/anaconda3/envs/axonDeepSegEnv1/lib/python3.8/site-` `packages/ivadomed/loader/mri2d_segmentation_dataset.py", line 152, in prepare_indices`
  `  raise RuntimeError('"length_2D" must be smaller or equal to image dimensions after resampling.')`
`RuntimeError: "length_2D" must be smaller or equal to image dimensions after resampling.`

The image in question is 2160 x 1440 pixels at a resolution of 0.0064 micron per pixel. 

The system running this package is Ubuntu 20.04 

Any help would be greatly appreciated.

Best,

Michael

**Comment by mathieuboudreau** [comment]
@mariehbourget I think this might be an issue that we used to solve by tweaking the resampling resolution, but now with ivadomed we don't have that parameter anymore. The issue stems from the fact that we cant create the disired patch size because his image resolutions are much smaller than the ones used by the model, right? Does IVADOMED have a solution to this problem, like we used to have in ADS?

**Comment by mathieuboudreau** [comment]
Sorry, I meant that we were able to tweek the resolution as such that it did not match the "actual" resolution. This comes back to the idea that I think we need a "zoom" feature to disconnect the patche size vs resolution issue, as often when we were making the users tweak the resolution we were really just making them change the patch sizes, practically

**Comment by mariehbourget** [comment]
@GrimmSnark, here is the explanation/solution, so you can use the BF and SEM models on your images.

The TEM model works at a resolution of 0.01 micrometer per pixel, since this is close to your image resolution of 0.0064 microns/pixels, you don't get the error with the TEM model.

However, the BF and SEM models works at a resolution of 0.1 micrometer per pixel.
The error you get is due to the minimum patch size of 512x512 of the BF model and 256x256 of the SEM model after resampling to their resolution of 0.1 micrometer per pixel.

The resampling in ADS goes like this:
`dimension of the image (in pixels) * pixel size (in microns/pixels) / resolution of the model (in microns/pixel)` and the result must be greater than the `patch size (in pixels)`.

For example, with your image of `2160x1140`, `pixel_size=0.0064` and `model_resolution=0.1`, you will have the following result (on the smallest dimension of `1440`):
`1440*0.0064/0.1 = 92`

To apply the SEM model, you need to artificially increase the size of the image with padding (i.e. add empty pixels around the borders) so the smaller dimension is 4000 (or more) to have a result equal of greater than 256.
`4000*0.0064/0.1 = 256`

On the BF model, you will need to pad to a minimum of 8000 pixels to have a result equal of greater than 512.
`8000*0.0064/0.1 = 512`

Please let us know if that resolve the issue.
Don't hesitate to contact us if your have questions, we will be happy to help!

@mathieuboudreau, there is a warning in our documentation about this issue but it is in the [notebooks](https://axondeepseg.readthedocs.io/en/latest/documentation.html#jupyter-notebooks) section and not very detailed. That seems like something that should be part of the [Existing models](https://axondeepseg.readthedocs.io/en/latest/documentation.html#existing-models) section, and maybe with the above details to help our users, what do you think?

**Comment by mathieuboudreau** [comment]
@GrimmSnark would it be possible for you to share a sample image, so that we could try on our side a solution?

**Comment by GrimmSnark** [comment]
Hello,

Thank you for the very helpful suggestions. I have not had the opportunity to try the padded images but I think that will solve the issue. Regardless, attached is a sample image which causes the aforementioned error. The resolution for this image is resolution of 0.0064 micron per pixel. 
[LM_58_G.zip](https://github.com/neuropoly/axondeepseg/files/8108752/LM_58_G.zip)


All the best,

Michael

**Comment by mathieuboudreau** [comment]
Thanks @GrimmSnark !

@mariehbourget and I played around a bit with some of the ADS settings on your dataset, and here are some reflections//results:

* Because of your datasets contrast, we saw better results using the TEM model.
* Using the TEM model instead of the SEM model changes our internal resolution during segmentation, so there may be less of a need to do padding to avoid the error you were getting with SEM.
* Using the TEM model with your true resolution of 0.0064 microns, we saw better results in segmenting large axons (at the cost of missing small axons):

![LM_58_G_seg-axonmyelin](https://user-images.githubusercontent.com/1421029/155013470-9e675c6b-ae88-44a4-81a8-78b143317a43.png)

* By using the TEM model but changing the input resolution in ADS to 0.0134 (which essentially, what it will be doing is "zooming" in the patches of the images during the segmentation to your image), we saw better results for small axons (at the cost of worse segmentations on your larger axons):

![LM_58_G_seg-axonmyelin (1)](https://user-images.githubusercontent.com/1421029/155013631-90f4a7d0-350d-4730-8570-757257364740.png)

* Applying padding did not provide good results in our tests.

I think the consensus internally in our group is that if we were in your place, it would be better to use a resolution 0.0134 **during the segmentation phase only** in ADS (note that when creating morphology files, you should use your true resolution value to get accurate values), and then manually correct the segmentation of the large axons using the FSLeyes plugin we provide. Manually fixing/manually segmenting a few large axons is much less time consuming than fixing/manually segmenting many small axons, in our experience.

Hope some of this information is helpful!

**Comment by GrimmSnark** [comment]
Thank you very much for all your advice, the labelling is working much better now!
