### ISSUE TITLE
Add feature to filter axons in segmented images using a list of axon indices

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#628]
Example workflow:

* Segment an image
* Create morphometrics file
* Identify axons in morphometrics file that have unlikely properties (eg very small or large g-ratios, single pixel axons, etc)
* Take the list of axons indices from the previous step, and feed it to this new function with the segmented image
* Produce new segmented image with filtered axons identified by the indices.

**Comment by Stoyan-I-A** [comment]
I did some testing for this feature, here's the report: https://docs.google.com/presentation/d/1F2ENEVdZ4oyGRFt6k1kMKw9mbK1QvXPdtzeJrfRdHVA/edit#slide=id.p

**Comment by hermancollin** [comment]
Simple reminder: when we will fully implement this script/feature, we need to make sure to use the "batch removal" function instead of using iteratively the "single axon removal" function that @Stoyan-I-A wrote in #651 

IIUC, the most time-consuming part of this computation is applying the watershed. If we call the function for a single axon, the watershed segmentation will be computed everytime thus severely slowing down the process.

**Comment by mathieuboudreau** [comment]
This issue is a duplicate of #760 and #781, so will close
