### ISSUE TITLE
Add `--border-info` morphometrics flag

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#647]
Essentially, this comes from user feedback while working on #645. This flag would trigger a *border-info* mode which would do this:
- add the `border_touching` boolean column in the morph. file implemented in #645
- add the axonmyelin's bounding box coordinates
- save the original image with bounding boxes overlayed onto it (if it doesn't impact the morphometrics runtime too much). This would mostly be useful because it would give the user more insight on the way the morphometrics script "sees" the axons.

The only issue is that we'll need to add a parameter to `get_axon_morphometrics`, which will slightly change the API so we'll have to go over the notebooks too.

**Comment by Stoyan-I-A** [comment]
I'm reopening this issue because I found something we overlooked in #650.
[download_tests.py](https://github.com/axondeepseg/axondeepseg/blob/master/AxonDeepSeg/download_tests.py) has not been updated with the new url (of release [r20220607a](https://github.com/axondeepseg/data-testing/releases/tag/r20220607a)) for the new test data uploaded by @hermancollin.

In the new reference dataframe for `test_morphometrics_consistency` ([link to the test](https://github.com/axondeepseg/axondeepseg/blob/897daa50b1a68105cce359030fe65c8541088553/test/morphometrics/test_compute_morphometrics.py#L732)) there's a column called `border_touching` but in the master branch this parameter is called `image_border_touching` which causes the test to fail even if we set `return_border_info=True`.

**Comment by hermancollin** [comment]
@Stoyan-I-A Ah, I forgot about this. I released the test for `test_morphometrics_consistency` but when merging the first PR, I reverted it because I figured we should test this feature separately and more directly. I should have deleted this release tho.

`test_morphometrics_consistency` should not call `axondeepseg_morphometrics` with the `-b` flag, so the `image_border_touching` column shouldn't even be present for this test.
