### ISSUE TITLE
Problems opening fsleyes after ads_plugin.py

### ISSUE THREAD

**Issue by djcvan** [axondeepseg/axondeepseg#705]
Hello,
I am new to axondeepseg and am attempting to use the software on my laptop (Microsoft Windows [Version 10.0.22000.1335]). I have completed all the installation steps listed on the website (https://axondeepseg.readthedocs.io/en/latest/documentation.html#installation) but am having problems at the ads_plugin portion. I have been able to open the fsleyes program on the initial run through but when I add the plugin (ads_plugin.py) perminantly it closed me out of the fsleyes program and is not allowing me to open the function again. Subsequent attempts to type fsleyes into the prompt results in several seconds of cycling before returning me to the blank prompt without opening the fsleyes program (see code below). 

(djc_demo) C:\Users\daxcv\axondeepseg>fsleyes

(djc_demo) C:\Users\daxcv\axondeepseg>

If anyone has encountered this problem in the paste I would greatly appreciate any insight. 

Thank you, 
Dax

**Comment by mathieuboudreau** [comment]
Hi @djcvan !

As indicated in [our documentation](https://axondeepseg.readthedocs.io/en/latest/documentation.html#install-axondeepseg), because FSLeyes is only supported on Mac and Linux, the ADS plugin will not work.

However, @Stoyan-I-A has been developing a plugin for an alternative software which is Windows compatible, and the initial version of it should be available in the coming weeks. He can provide you with a better time estimate, likely after the holidays.

**Comment by djcvan** [comment]
Hello @mathieuboudreau,
Thank you for following up on this. I apologize for missing that segment on the website.

**Comment by mathieuboudreau** [comment]
No worries @djcvan =) We know this is a desired feature, and hope to make it available soon. Keep an eye out, or message us again for more info!
