### ISSUE TITLE
16-bit images cannot be loaded

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#709]
A recent interaction with a user that we have an ongoing project with recently highlighted an issue with 16-bit images. If the image is 16-bit, ADS tries to read it as an 8-bit image and the input is messed up (Looks like it reads the 8 LSBs? Loaded image looks like white noise). We somewhat discussed this during PR #669 but decided to deal with this in a separate PR and it slipped through the cracks. I wasn't aware that the default imread mishandled 16-bit images this badly. The user that reported this encountered it while performing annotations with fsleyes and the plugin. He said some of their samples were saved as 16-bit, so this is something that is likely to happen again.

To fix this, I'm not sure what we should do. We could look for the bitdepth of the image we are trying to load and pass it to imageio's imread?

Loosely related to #668 but this issue is higher priority IMO

**Comment by mathieuboudreau** [comment]
Did/can the user provide a sample image / output?

**Comment by hermancollin** [comment]
@mathieuboudreau I asked him for an example image but they said that converting the image to 8-bit before loading it in fsleyes solved the problem so they did not provide anything. To reproduce, you can try to load the 16b image from our test files in fsleyes. We sadly obtain this :sweat_smile: 

![Screenshot_20230116_161430](https://user-images.githubusercontent.com/83031821/212766921-600b43c0-2df2-492a-95cf-4709a7016ba2.png)

Looking at what the image is supposed to look like, it seems imread indeed reads the 8 less significant bits...

**Comment by mathieuboudreau** [comment]
Thanks!

It's likely cutting off the values after the 8 bits rather than doing a conversion. We could look into offering the option to converting to 8bit prior to processing (which I thought we were already doing, but I guess not?)

**Comment by mathieuboudreau** [comment]
So this all felt very familiar, and yes, it appears that this was a previous issues (twice!) that was resolved in a PR.

Issue 1: https://github.com/axondeepseg/axondeepseg/issues/166
PR: https://github.com/axondeepseg/axondeepseg/pull/243

Issue 2: https://github.com/axondeepseg/axondeepseg/issues/617

So, first step should be seeing when/where/why this behaviour changed from working to broken.

**Comment by mathieuboudreau** [comment]
Ok, so it seems like originally we did the conversion this way,

https://github.com/axondeepseg/axondeepseg/blob/fbbb03c44dc9e4b0409364b49265f453ac80d3c0/AxonDeepSeg/ads_utils.py#L265

but then recently changed to this way,

https://github.com/axondeepseg/axondeepseg/blob/f83a84241062ff8b56739d8ca694b6509540fad1/AxonDeepSeg/ads_utils.py#L283

This was done in this commit of PR #669 

https://github.com/axondeepseg/axondeepseg/pull/669/commits/99748d23ac1f61e2a013d6d62c56f1f125163072

implicitely because I was removing the 8 bit "option" for the imread arg. But this new way seems to be cutting off the image's bits, instead of doing the proper conversion.

Changing the line to this,

`img = imageio.core.image_as_uint(raw_img, bitdepth=8)`

Appears to fix the issue while maintaining the 8bit conversion. The image now loads correctly in FSLeyes,


<img width="1232" alt="Screenshot 2023-01-16 at 9 34 29 PM" src="https://user-images.githubusercontent.com/1421029/212790688-538f0823-3764-42a3-abdc-6bb161108e1b.png">

However, it reintroduces this warning "Lossy conversion from uint16 to uint8. Losing 8 bits of resolution. Convert image to uint8 prior to saving to suppress this warning.", but better to have a warning than a bug.

I'll make a PR with this quick fix and assign you @hermancollin
