### ISSUE TITLE
Handle PIP - archive or delete?

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#808]
**Describe the bug**
Feel free to add screenshots to illustrate the problem!

**To Reproduce**

4. See "Error 1955: Out of Time"

**Platform (please complete the following information):**
 - OS: [e.g. Mac OS "Flaming Flamingo", Fedora 99, Ubuntu 48.04]
 - AxonDeepSeg version number [e.g. 3.2.0, git master, etc.]

**Comment by psobolewskiPhD** [comment]
This seems like the most relevant place to ask:
Any plans to make this package more easily installable?
A proper python package would make it easier.

Also I had no idea there was a napari plugin, because it's not easily discoverable -- it's not on pypi or the napari-hub. Would be great if that was a python package that depended on the full ADS.
I'd love to be able to have someone use the napari conda installer (aka the bundle) and then use the plugin manager to install this using conda/pip from within napari!

**Comment by mathieuboudreau** [comment]
@psobolewskiPhD thanks for the feedback - we had stopped releasing on pip a few years ago as we had started to use FSLeyes and made a plugin for that, and the installation of that software wasn't really compatible.

Recently (like two weeks ago), @joshuacwnewton updated our installation configuration to simplify it. I still am not sure if pipy would be right, we'll discuss it in our group meeting to see if it's useful and/or possible, but adding our plugin to the napari-hub certainly sounds like a good idea. I'm tagging @Stoyan-I-A to see what his opinion is on this, we'd probably do so with our next major release (v5), which should come soon after our napari/mac issue is resolved: https://github.com/napari/napari/issues/7259

**Comment by joshuacwnewton** [comment]
> Any plans to make this package more easily installable?

What I've tried to do in #800 is provide an [installer script](https://github.com/axondeepseg/axondeepseg/blob/b2533989851d204ca575dc502f7b920b6ec58beb/install_ads) (similar to [FSL's installer script](https://fsl.fmrib.ox.ac.uk/fsl/docs/#/install/linux)) that runs all of the additional commands that are necessary before and after the `pip` step. I'm hoping it will help save our users the hassle of having to manage conda/Python installations, virtual environments, and various large dependencies.

If you would like to look at a sneak preview of what the new installation instructions will become, please visit [the new WIP Installation section](https://github.com/axondeepseg/axondeepseg/blob/b2533989851d204ca575dc502f7b920b6ec58beb/docs/source/documentation.rst#installation). I hope that you find these new steps to be more approachable. :)

> A proper python package would make it easier.

As far as a `pip` install specifically, while I can't speak for ADS as a whole, I do have experience with [SCT](https://spinalcordtoolbox.com/) (a similar sister project within the NeuroPoly lab). And, we've found that PyPI hosting comes with limitations that make it difficult to fully adopt, especially for projects based on large non-Python dependencies such as deep learning models. There are [certain things that `pip` cannot do by itself](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/1526), which is how we end up with all of these extra commands before and after the actual `pip install` step in the first place. 

For what it's worth, SCT has been using a similar installer script for years to good success, so I'm hopeful that the upcoming changes to ADS will make things easier. But, we always welcome feedback, too. The mention of `napari-hub` in particular is especially interesting to me, and I would be curious to look more into it, so thank you for sharing your thoughts. :)

**Comment by psobolewskiPhD** [comment]
First, I want to be clear that as someone who 1) also develops open-source software in Python (hobby) and 2) supports users in a research  computing environment (day job), I 100% support you in making decisions that work for you and your users. Nothing I say is intended as criticism, merely my 2 cents, and I 100% recognize that the python packaging situation is a lot worse than it should be -- nothing like spending an hour of an Intro to Python workshop dealing with install issues!
It sucks.

So with that said:
The WIP installation instructions you shared are clear and certainly easy to follow. The prompts in the script are commendable.
I'm not a bash script guru but I'm concerned about two things:
1. using miniconda: this has severe licensing issues when used in an organization, see https://prefix.dev/blog/towards_a_vendor_lock_in_free_conda_experience for a cogent summary. 
2. Will the script install a duplicate conda setup if the user already has an alternate conda setup?miniforge conda, mamba, micromamba or pixi?
3. the enforcing of rosetta emulation can be problematic (see recent napari issue https://github.com/napari/napari/issues/7259#issuecomment-2348868226 ) and I'd like to think is un-needed (I've been using an arm64 only environment since 2021)

Note: you essentially trade the need for the end user to have a conda or python install for having `git` installed. The advantages of this trade-off are not obvious to me -- git to me is a more developer/coder specific tool?
Additionally, if everyone has a custom install script/process, then are we gaining much from an end user-perspective?

Despite the challenges, I think there are real advantages to making a conventional python package. Your custom scripts could certainly remain and expand upon that or offer advanced solutions.
1. It makes it easier to incorporate into existing workflows/pipelines for people who already have some sort of python savvy, such as their own projects or environments or containers.
2. It makes it so other people can make packages that depend on your package. So for example, a napari-axondeepseg plugin--from you or someone else--could depend on axondeepseg. Note: to be available in the napari GUI installer and on the hub a napari plugin does need to be a package, see: https://www.napari-hub.org/faq Or someone could include axondeepseg with some other tool, whether via conda or pip.
3. With a python package on pypi, it's easier to make a conda-forge package which can facilitate various complex dependencies. You could certainly recommend people use conda to install it and not pip!

So in this case, with a pip/conda package available along side a napari plugin, using the napari GUI installer (https://napari.org/stable/tutorials/fundamentals/installation_bundle_conda.html) a user could then install everything without ever facing a command line or terminal.

Now I recognize that GPU acceleration is tricky, but you could aim for cpu out of the box and provide support for that using custom install instructions. I do think the situation is improving, particularly using conda-forge.

In terms of downloading models or whatnot, you can always do that from within your package. Lots of python packages download sample data or ML models when you first call certain functions/methods, so that I think is the easiest piece of this puzzle.

**Comment by mathieuboudreau** [comment]
Thanks a lot for your insights/inputs @psobolewskiPhD - it's very appreciate, and so is your tool Napari!

@joshuacwnewton will likely have some inputs on the current installation flow; he's been managing another widely used tool (SpinalCordToolbox - https://github.com/spinalcordtoolbox/spinalcordtoolbox) developed in our lab that has been using this installation procedure for a while now, though even Joshua will say some things could be improved.

I'll just chime in and maybe give you some of my thoughts and reasoning as to why we opted to gradually turn to the current installation procedure.

>using miniconda: this has severe licensing issues when used in an organization, see https://prefix.dev/blog/towards_a_vendor_lock_in_free_conda_experience for a cogent summary.

Many if not most of our users are not developers, and several years ago we had determined that providing direct links to miniconda binaries was the most simple and efficient way to ask our users to setup a virtual environment on all three major operating systems. I also saw that recent Anaconda-related news, and internally we decided to wait and see how the dust settles before changing anything major on our end. However, as your link indicates, if the `conda-forge` channel is set (which we were doing here: ) instead of the `default` anaconda channel, then it should be free to use regardless of application/size.

>Will the script install a duplicate conda setup if the user already has an alternate conda setup?miniforge conda, mamba, micromamba or pixi?

Yes, with our new installation this is done by design. Over the past year and a half or two years, some of us (particularly ADS developpers) have had increasingly long installation times for ADS using our "main" conda installed on our system, as 1) we were mainly using conda-forge instead of pip for most of our dependencies, and 2) conda was taking a LONG time resolving depedencies when a lot of wheels existed already locally (I think because it thinks its more efficient to compare all the versions you have cached first). By a long time, I mean sometimes over an hours done resolving dependencies. Using a standalone miniconda + just pip now fairly guarantees a quick version resolve, and for me I've cut down my installation time from over an hours sometimes to less than 5 minutes. For more experienced developers, we *could* give instructions on how to install things locally (it's fairly straightforward), but I think both our users (and us developpers) will benefit from a simpler and quicker installation procedure.

>the enforcing of rosetta emulation can be problematic (see recent napari issue https://github.com/napari/napari/issues/7259#issuecomment-2348868226 ) and I'd like to think is un-needed (I've been using an arm64 only environment since 2021)

I agree, and I suggested in our PR to add a miniforge option for ARM systems (which resolved that issue for me). We could possibly replace miniconda with miniforge, I'm haven't checked miniforge's cross-platform compatibility though. We also explored using mamba: https://github.com/axondeepseg/axondeepseg/pull/680

As for your suggestion to make a pip package, we did do this before (as you can see from this issue), but had to stop when we started making a plugin for FSLeyes (which could only be installed via conda back then). But now that we've switched to napari, this isn't a limitation anymore. Another reason why we stopped was because very few (if any, tbh) users were installing AxonDeepSeg as a dependency to then be imported and used in their own software scripts; our users are mainly people who want to load images and get a segmentation from it, and then morphometrics from those segmentations.

We discussed last Friday at our team meeting and landed on this idea: we're going to keep our installation as it is for the moment, as we're very close to a v5 release that I know several users are waiting for. Parallel to this, we're going to look into how feasible it might be to branch off our main release occasionally, and edit that branch such that it can be made into a pipy release. We'd be quite happy to be able to be listed on the napari plugin hub, so maybe we could update the release whenever we have another major AxonDeepSeg release, but not maintain the pipy release as often as we do our main branch. One other potential limitation to pipy (I'm not sure though) is that our recent deep learning models are quite large (~1+ gb I think), so there might be additional steps that the users would need to do to download these outside of the pipy wheel, but we'll see when we get to that.

**Comment by mathieuboudreau** [comment]
Finally got around to this issue - archived it by pushing a release that then when trying `axondeepseg` after pip installation, will print a message redirecting to this github repo.

```
(base) mathieuboudreau@Mathieus-MacBook-Pro axondeepseg % conda create -n test_env
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 24.11.1

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.11.1



## Package Plan ##

  environment location: /Users/mathieuboudreau/mambaforge/envs/test_env



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) mathieuboudreau@Mathieus-MacBook-Pro axondeepseg % conda activate test_env
(test_env) mathieuboudreau@Mathieus-MacBook-Pro axondeepseg % pip install axondeepseg
zsh: command not found: pip
(test_env) mathieuboudreau@Mathieus-MacBook-Pro axondeepseg % conda install pip
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 24.11.1

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.11.1



## Package Plan ##

  environment location: /Users/mathieuboudreau/mambaforge/envs/test_env

  added / updated specs:
    - pip


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2024.12.14 |       hf0a4a13_0         153 KB  conda-forge
    libexpat-2.6.4             |       h286801f_0          63 KB  conda-forge
    liblzma-5.6.3              |       h39f12f2_1          97 KB  conda-forge
    libmpdec-4.0.0             |       h99b78c6_0          68 KB  conda-forge
    libsqlite-3.47.2           |       h3f77e49_0         831 KB  conda-forge
    pip-24.3.1                 |     pyh145f28c_2         1.2 MB  conda-forge
    python-3.13.1              |h4f43103_102_cp313        12.3 MB  conda-forge
    python_abi-3.13            |          5_cp313           6 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        14.7 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h99b78c6_7 
  ca-certificates    conda-forge/osx-arm64::ca-certificates-2024.12.14-hf0a4a13_0 
  libexpat           conda-forge/osx-arm64::libexpat-2.6.4-h286801f_0 
  libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5 
  liblzma            conda-forge/osx-arm64::liblzma-5.6.3-h39f12f2_1 
  libmpdec           conda-forge/osx-arm64::libmpdec-4.0.0-h99b78c6_0 
  libsqlite          conda-forge/osx-arm64::libsqlite-3.47.2-h3f77e49_0 
  libzlib            conda-forge/osx-arm64::libzlib-1.3.1-h8359307_2 
  ncurses            conda-forge/osx-arm64::ncurses-6.5-h7bae524_1 
  openssl            conda-forge/osx-arm64::openssl-3.4.0-h39f12f2_0 
  pip                conda-forge/noarch::pip-24.3.1-pyh145f28c_2 
  python             conda-forge/osx-arm64::python-3.13.1-h4f43103_102_cp313 
  python_abi         conda-forge/osx-arm64::python_abi-3.13-5_cp313 
  readline           conda-forge/osx-arm64::readline-8.2-h92ec313_1 
  tk                 conda-forge/osx-arm64::tk-8.6.13-h5083fa2_1 
  tzdata             conda-forge/noarch::tzdata-2024b-hc8b5060_0 


Proceed ([y]/n)? y


Downloading and Extracting Packages
                                                                                                                                                                                                         
Preparing transaction: done                                                                                                                                                                              
Verifying transaction: done                                                                                                                                                                              
Executing transaction: done                                                                                                                                                                              
(test_env) mathieuboudreau@Mathieus-MacBook-Pro axondeepseg % pip install axondeepseg
Collecting axondeepseg
  Downloading AxonDeepSeg-4.9999999-py2.py3-none-any.whl.metadata (611 bytes)
Downloading AxonDeepSeg-4.9999999-py2.py3-none-any.whl (3.0 kB)
Installing collected packages: axondeepseg
Successfully installed axondeepseg-4.9999999
(test_env) mathieuboudreau@Mathieus-MacBook-Pro axondeepseg % axondeepseg
Pipy installation of AxonDeepSeg is no longer supported, please visit https://github.com/axondeepseg/axondeepseg for installation isntructions.
(test_env) mathieuboudreau@Mathieus-MacBook-Pro axondeepseg % 
```
